import Head from "next/head";
import Image from "next/image";
import { Poppins } from "@next/font/google";
import styles from "@/styles/Home.module.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
          integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
          crossorigin="anonymous"
          referrerpolicy="no-referrer"
        />
      </Head>

      <main className={`${styles.main} text-white`} style={poppins.style}>
        <header className="min-h-screen relative isolate w-full grid place-items-center">
          <div className="bg-pink-900 h-[60%] absolute left-0 top-0 right-0 z-[-1]"></div>
          <nav className="w-full absolute left-0 right-0 top-0">
            <div className="container py-3  w-full flex justify-between items-center">
              <div className="text-white text-xl font-regular">Harris</div>

              <div className="nav__items flex gap-2">
                <a
                  className="px-3 py-1 rounded-full outline-none hover:bg-white hover:text-black transition-all duration-150"
                  href="#about"
                >
                  About
                </a>
                <a
                  className="px-3 py-1 rounded-full outline-none hover:bg-white hover:text-black transition-all duration-150"
                  href="#resume"
                >
                  Resume
                </a>
                <a
                  className="px-3 py-1 rounded-full outline-none hover:bg-white hover:text-black transition-all duration-150"
                  href="#project"
                >
                  Project
                </a>
                <a
                  className="px-3 py-1 rounded-full outline-none hover:bg-white hover:text-black transition-all duration-150"
                  href="#contact"
                >
                  Contact
                </a>
              </div>
            </div>
          </nav>

          <div className="container grid place-items-center">
            <div
              id="about"
              className="flex justify-center items-start rounded-md overflow-hidden isolate relative after:absolute backdrop-blur-[1rem] after:inset-0 after:bg-black after:opacity-30 bg-transparent after:z-[-1]"
            >
              <div className="img aspect-[9/12] h-[20rem]">
                <img
                  src="/foto_pelajar.jpg"
                  className="w-full h-full object-cover"
                />
              </div>
              <div className="content px-6 py-4 h-[20%] flex flex-col justify-start w-full">
                <h1 className="text-2xl font-normal tracking-[1px] uppercase mb-2">
                  About Me
                </h1>
                <p className="text-sm font-light tracking-[2px] mb-6 border-l-2 border-pink-400 pl-4">
                  PROJECT CV - NEXTJS
                </p>
                <p>
                  I am Harris, a 16 year old student living in Denpasar. I
                  started learning coding when I was in high school. I'm
                  learning to make websites and make a simple Memory Game with
                  my own code. Since then, I became more and more interested and
                  started learning more stuffs, for example Javascript Games
                  using Phaser and also Web Development
                </p>
              </div>
            </div>
          </div>
        </header>

        <section id="project">
          <div className="parent">
            <div className="flex flex-row gap-96 mt-6 ml-5 mr-5 border-b-2 border-[#80E3FF]">
              <div className="project-items flex-col">
                <span className="text-[#80E3FF] text-4xl font-bold">
                  Projects
                </span>
                <br />
                <br />

                <div className="project-container">
                  <div className="project flex">
                    <img
                      src="/snake.png"
                      alt="snake"
                      className=" w-[450px] h-[260px]"
                    />
                    <span className="font-medium text-[#6E6D6D] text-1xl indent-0  p-4">
                      Lorem ipsum dolor sit amet consectetur adipisicing elit.
                      Mollitia blanditiis dolorem eos explicabo, alias provident
                      quod, <br />
                      tempora sunt commodi officia voluptatem excepturi
                      corporis, architecto necessitatibus id praesentium vel
                      distinctio in!
                    </span>
                  </div>
                  <br />
                  <div className="project flex mb-6">
                    <img
                      src="/sahara.png "
                      alt="sahara"
                      className=" w-[450px] h-[260px]"
                    />
                    <span className="font-medium text-[#6E6D6D] text-1xl inset-0 p-4">
                      Lorem ipsum dolor, sit amet consectetur adipisicing elit.
                      A consequuntur quae laudantium amet nam possimus iure
                      maxime eos eum, eius iste alias. Iure natus sunt harum
                      aliquam fugiat? Alias, explicabo!
                    </span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section className="contact h-[90vh]">
          <div className="flex flex-row gap-96 ml-5 mr-5 mt-6">
            <span className=" text-[#80E3FF] text-4xl font-bold ">Contact</span>
            <br />
            <br />
            <div className="form-container">
              <div className="input-container">
                <div className="form-input">
                  <input type="text" className="input-item" name="name" />
                  <label htmlFor="name">Name</label>
                </div>
              </div>
              <div className="input-container">
                <div className="form-input">
                  <input type="text" className="input-item" name="city" />
                  <label htmlFor="city">City</label>
                </div>
              </div>
              <div className="">
                <div className="">
                  <input type="email" className="" name="email" />
                  <label htmlFor="email"></label>
                </div>
              </div>
              <div className="">
                <div className="">
                  <textarea name="message" id="" cols="52" rows="8"></textarea>
                  <label htmlFor="message" className="">
                    Message
                  </label>
                </div>
              </div>
            </div>
          </div>
        </section>

        <footer
          className="h-16 md-m:text-white shadow-md bg-[#80E3FF] border-t z-20 border border-neutral-400 grid place-items-center"
          id="footer"
        >
          <div className="container footer__container flex justify-center items-center font-normal opacity-75 text-sm">
            <p className=" text-black">
              Copyright © 2023 Harris . All rights reserved
            </p>
          </div>
          <div className="flex gap-4">
            <a href="https://instagram.com/hiihrris?igshid=YWJhMjlhZTc=">
              <i class="fa-brands fa-instagram"></i>
            </a>
            <a href="mailto:acmadharris225@gmail.com">
              <i class="fa-regular fa-envelope"></i>
            </a>
          </div>
        </footer>
      </main>
    </>
  );
}
